# Generated by Django 5.0.2 on 2024-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ubicaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código postal"
                    ),
                ),
                (
                    "nombre_ciudad",
                    models.CharField(max_length=50, verbose_name="Nombre de la ciudad"),
                ),
                (
                    "nombre_calle",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nombre de la calle"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato de seguimiento",
                "verbose_name_plural": "Datos de seguimiento",
            },
        ),
    ]
