# Generated by Django 5.0.2 on 2024-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_ubicaciones_seguridad_zona"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delegacion_delito",
                    models.CharField(
                        max_length=30, verbose_name="Delegación del delito"
                    ),
                ),
                (
                    "calle_delito",
                    models.CharField(max_length=30, verbose_name="Calle del delito"),
                ),
                (
                    "colonia_delito",
                    models.CharField(max_length=30, verbose_name="Colonia del delito"),
                ),
                (
                    "codigop_delito",
                    models.CharField(
                        max_length=10, verbose_name="Código Postal Delito"
                    ),
                ),
                (
                    "tipo_delito",
                    models.CharField(
                        choices=[
                            ("0", "robo"),
                            ("1", "asalto"),
                            ("2", "abuso"),
                            ("3", "venta de drogas"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Tipo de Delito",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción del delito"),
                ),
            ],
            options={
                "verbose_name": "Registro de delito",
                "verbose_name_plural": "Registros de delitos",
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código postal"
                    ),
                ),
                (
                    "nombre_ciudad",
                    models.CharField(max_length=50, verbose_name="Nombre de la ciudad"),
                ),
                (
                    "nombre_calle",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nombre de la calle"
                    ),
                ),
                (
                    "seguridad_zona",
                    models.CharField(
                        choices=[
                            ("0", "segura"),
                            ("1", "insegura"),
                            ("2", "zona delictiva"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Seguridad de la zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato de seguimiento",
                "verbose_name_plural": "Datos de seguimiento",
            },
        ),
        migrations.DeleteModel(
            name="ubicaciones",
        ),
    ]
