# Generated by Django 5.0.2 on 2024-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0004_remove_ubicacion_nombre_calle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacion",
            name="codigo_postal",
            field=models.CharField(max_length=10, verbose_name="Código postal"),
        ),
        migrations.AlterField(
            model_name="ubicacion",
            name="nombre_colonia",
            field=models.CharField(max_length=50, verbose_name="Nombre de la colonia"),
        ),
    ]
