# Generated by Django 5.0.2 on 2024-05-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0005_alter_ubicacion_codigo_postal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delito",
            name="codigop_delito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="location.ubicacion"
            ),
        ),
    ]
