# Generated by Django 5.0.2 on 2024-05-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0006_alter_delito_codigop_delito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delito",
            name="tipo_delito",
            field=models.CharField(
                choices=[
                    ("0", "robo"),
                    ("1", "asalto"),
                    ("2", "abuso"),
                    ("3", "venta de drogas"),
                    ("4", "homicidio"),
                ],
                default="0",
                max_length=1,
                verbose_name="Tipo de Delito",
            ),
        ),
    ]
