# Generated by Django 5.0.2 on 2024-05-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0007_alter_delito_tipo_delito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delito",
            name="tipo_delito",
            field=models.CharField(
                choices=[
                    ("0", "robo"),
                    ("1", "asalto"),
                    ("2", "abuso"),
                    ("3", "venta de drogas"),
                    ("4", "homicidio"),
                    ("5", "secuestro"),
                    ("6", "feminicidio"),
                ],
                default="0",
                max_length=1,
                verbose_name="Tipo de Delito",
            ),
        ),
        migrations.AlterField(
            model_name="ubicacion",
            name="nombre_colonia",
            field=models.CharField(max_length=70, verbose_name="Nombre de la colonia"),
        ),
        migrations.CreateModel(
            name="Delincuente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_delincuente",
                    models.CharField(
                        max_length=40, verbose_name="Nombre del delincuente"
                    ),
                ),
                (
                    "proceso",
                    models.CharField(
                        max_length=30,
                        verbose_name="¿Se encuentra en proceso el delincuente?",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/empleado"
                    ),
                ),
                (
                    "codigop_delincuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datos de delicuente",
                "verbose_name_plural": "Datos de los delincuentes",
            },
        ),
    ]
