# Generated by Django 5.0.2 on 2024-05-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0008_alter_delito_tipo_delito_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delincuente",
            name="descripcion_delincuente",
            field=models.TextField(blank=True, verbose_name="Descripción del delito"),
        ),
        migrations.AlterField(
            model_name="delincuente",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/delincuente",
                verbose_name="Imagen del delincuente",
            ),
        ),
    ]
