# Generated by Django 5.0.2 on 2024-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0009_delincuente_descripcion_delincuente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delincuente",
            name="descripcion_delincuente",
            field=models.TextField(
                blank=True, verbose_name="Describe las características del delincuente"
            ),
        ),
        migrations.AlterField(
            model_name="delincuente",
            name="proceso",
            field=models.CharField(
                max_length=100, verbose_name="¿Se encuentra en proceso el delincuente?"
            ),
        ),
    ]
